name: CICD
on: [push]

env:
  DB_URL: postgresql://user:pass@127.0.0.1:5432/db
  IMAGE: auth_service

jobs:
  run_tests:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 1s
          --health-retries 10

    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install poetry
      - run: make install
      - run: make lint
      - run: make test
      - run: make cov
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: echo Hello


# -------------- TEST ENV --------------------- #

  test_build:
    needs: run_tests
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/develop'

    steps:

      - name: Get SHORT_SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_AUTH_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            cr.yandex/${{ secrets.YC_TEST_CR_ID }}/auth_service:${{ env.SHORT_SHA }}
            cr.yandex/${{ secrets.YC_TEST_CR_ID }}/auth_service:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}



  test_deploy:
    needs: test_build
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/develop'
    env:
          SSH_USER_HOST: ${{ secrets.YC_TEST_VM_USER_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.YC_TEST_VM_SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.YC_TEST_VM_SSH_KNOWN_HOSTS }}

    steps:

      - name: Get SHORT_SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

      - name: Pull image
        run: ssh $SSH_USER_HOST ./pull_image.sh $IMAGE $SHORT_SHA

      - name: Run migrations
        run: ssh $SSH_USER_HOST ./app/auth_service/run_migrations.sh $IMAGE $SHORT_SHA

      - name: Run service
        run: ssh $SSH_USER_HOST ./app/auth_service/update_service.sh $IMAGE $SHORT_SHA



